#!/usr/bin/python
# Downloads the current "Astronomy Picture of the Day" from nasa.gov and sets as wallpaper
# 
# Installation steps:
# Run install.sh OR do the following:
# - store this file somewhere and take note of the path
# - change WALLPAPER_DIR to some folder in your home directory
#   and create the folder
# - make it executable:
#   chmod a+x /path/to/change_wallpaper
# - follow instructions given in the .plist file to make it run daily

FEED_URL = "http://apod.nasa.gov/apod/"
WALLPAPER_DIR = "/path/to/wallpaper/directory"
SLEEP_INTERVAL = 60

import subprocess, re, datetime
from urllib import urlopen, urlretrieve
import os.path, os
import time

def main():
    print "change_wallpaper - "+datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    time_multiplier = 1
    while True:
        try:
            xml = urlopen(FEED_URL).read()
        except:
            sleep_time = SLEEP_INTERVAL*time_multiplier
            time.sleep(sleep_time)
            time_multiplier += 1
            continue
        break
    m = re.search(r"a href=\"(image/.*?)\"", xml)
    if (m == None):
    	print "No image found."
    	exit(1)
    #m = re.search(r"img src=\"(.*?)\"", xml)
    first_img = FEED_URL + m.group(1)
    name = re.sub(r"^.*/", "", first_img)
    filename = "%s/%s-%s" % (WALLPAPER_DIR, str(datetime.date.today()), name)

    print "Image URL: ", first_img
    print "Filename: ", name
    print "Target file: ", filename
    if not (os.path.isdir(WALLPAPER_DIR)):
        print "Wallpaper directory " + WALLPAPER_DIR + " does not exist."
        exit()
    elif os.path.isfile(filename):
        print "File already exists."
    else:
        print "Downloading..."
        urlretrieve(first_img, filename)

    set_desktop_background(filename)

SCRIPT = """/usr/bin/osascript -s o<<END
tell application "Finder"
set desktop picture to POSIX file "%s"
end tell
END"""

def set_desktop_background(filename):
    print "Changing wallpaper..."
    #subprocess.Popen(SCRIPT%filename, shell=True)
    subprocess.check_call(SCRIPT%filename, shell=True)

main()
